# Generated by Django 5.0.6 on 2026-08-31 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Moment the reading was taken. Hypertable partition column.",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Temperature in degrees Celsius.",
                        max_digits=5,
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Relative humidity as a percentage (0–100).",
                        max_digits=5,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="The device that produced this reading.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading",
                "verbose_name_plural": "Readings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="readings_re_device__e9d089_idx",
                    )
                ],
            },
        ),
                migrations.RunSQL(
            sql="""
                ALTER TABLE readings_reading
                    DROP CONSTRAINT readings_reading_pkey;
                ALTER TABLE readings_reading
                    ADD PRIMARY KEY (id, timestamp);
                SELECT create_hypertable(
                    'readings_reading',
                    'timestamp',
                    if_not_exists => TRUE
                );
            """,
            reverse_sql="SELECT 1;",
        ),
    ]
